use_frameworks!

target 'TimeUIList_Example' do
  pod 'TimeUIList', :path => '../'

  target 'TimeUIList_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
    pod 'NFALunarUtil'
    pod 'NFAToolkit'
    pod 'NFATipsUI'
  end
end
